# Application properties for the League Service
server.port=8081
spring.application.name=league-service

# datasource configuration
spring.datasource.url=jdbc:h2:mem:leaguedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update